import json
import logging
from typing import Protocol

from langchain_core.language_models.chat_models import BaseChatModel
from pydantic import BaseModel, ValidationError

from app.config import Settings
from app.models.frames import ObjectiveAnalysis, ProcedureExtraction
from app.models.requirement import Requirement, RequirementExtraction
from app.models.work_request import WorkRequest


logger = logging.getLogger(__name__)


class LLMProvider(Protocol):
    def chat(self, prompt: str) -> str:
        ...

    def chat_json(self, prompt: str, schema: type[BaseModel], retries: int = 2) -> BaseModel:
        ...

    def analyze_objective(self, work_request: WorkRequest) -> ObjectiveAnalysis:
        ...

    def extract_procedures(self, work_request: WorkRequest) -> ProcedureExtraction:
        ...

    def extract_requirements(self, work_request: WorkRequest) -> RequirementExtraction:
        ...


class MockLLMProvider:
    """Deterministic provider for local development and tests."""

    def chat(self, prompt: str) -> str:
        return f"Mock response for: {prompt}"

    def chat_json(self, prompt: str, schema: type[BaseModel], retries: int = 2) -> BaseModel:
        raise NotImplementedError("mock provider uses typed extraction methods directly")

    def analyze_objective(self, work_request: WorkRequest) -> ObjectiveAnalysis:
        return ObjectiveAnalysis(
            objective=(
                f"Determine and complete the requirements necessary "
                f"to achieve: {work_request.goal}"
            ),
            current_situation=(
                work_request.current_status
                or "Initial state. Work has not been defined yet."
            ),
            success_criteria=(
                work_request.success_criteria
                or ["Success criteria confirmed with the requester"]
            ),
            constraints=(
                work_request.constraints
                or ["No explicit constraints provided; clarify before execution"]
            ),
            stakeholders=[person.name for person in work_request.people] or ["Task owner"],
            decision_makers=[role for role in work_request.roles] or [
                "Requesting manager"
            ],
            external_dependencies=(
                work_request.resources
                or ["No external dependencies were listed"]
            ),
            timeline_flags=[
                f"Deadline: {work_request.deadline.isoformat()}"
                if work_request.deadline
                else "No explicit deadline set"
            ],
            priority_flags=[f"Priority: {work_request.priority}"],
            notes="Objective analysis generated by the deterministic mock provider.",
        )

    def extract_procedures(self, work_request: WorkRequest) -> ProcedureExtraction:
        return ProcedureExtraction(
            summary=(
                "No procedure documents were indexed for this goal, so "
                "execution relies on defined requirements and approvals."
            ),
            procedures=[],
            notes=[
                "Ingest organizational procedure documents to ground execution.",
            ],
        )

    def extract_requirements(self, work_request: WorkRequest) -> RequirementExtraction:
        return RequirementExtraction(
            requirements=[
                Requirement(
                    id="req_1",
                    category="process",
                    text="Define the sequence of work needed to reach the objective",
                    rationale="Work must be broken into an ordered, executable sequence.",
                    relevant_tasks=["task_1"],
                ),
                Requirement(
                    id="req_2",
                    category="policy",
                    text="Identify the organizational policies that govern this work",
                    rationale="Policies determine what is permitted and required.",
                    relevant_tasks=["task_2"],
                ),
                Requirement(
                    id="req_3",
                    category="approval",
                    text="Obtain approval from decision makers before finalizing changes",
                    rationale="Changes need authorized sign-off before execution.",
                    relevant_tasks=["task_3"],
                ),
                Requirement(
                    id="req_4",
                    category="evidence",
                    text="Confirm that success criteria and required information are available",
                    rationale="Evidence must be available to verify completion.",
                    relevant_tasks=["task_4"],
                ),
            ]
        )


def _clean_json_response(content: str) -> str:
    content = content.strip()
    if content.startswith("```json"):
        content = content[7:]
    elif content.startswith("```"):
        content = content[3:]
    if content.endswith("```"):
        content = content[:-3]
    return content.strip()


class LangChainStructuredProvider:
    """
    Structured LLM provider built on an OpenAI-compatible chat model
    (NVIDIA NIM, OpenRouter, vLLM, OpenAI).
    """

    def __init__(self, llm: BaseChatModel) -> None:
        self.llm = llm

    def chat(self, prompt: str) -> str:
        response = self.llm.invoke(prompt)
        content = response.content
        if isinstance(content, str):
            return content
        return "".join(str(part) for part in content)

    def chat_json(self, prompt: str, schema: type[BaseModel], retries: int = 2) -> BaseModel:
        schema_json = json.dumps(schema.model_json_schema(), indent=2)
        instruction = f"""
You are an advisory workplace operations planner.

Return ONLY valid JSON that conforms exactly to this schema:

{schema_json}

Rules:
- Return JSON only.
- Do not wrap the JSON in Markdown code fences.
- Do not include explanations outside the JSON.
- Prefer conservative effort estimates using one of the allowed values.
"""
        last_error: Exception | None = None
        for attempt in range(retries + 1):
            raw = self.chat(instruction + "\n\n" + prompt)
            try:
                parsed = json.loads(_clean_json_response(raw))
                return schema.model_validate(parsed)
            except (json.JSONDecodeError, ValidationError) as error:
                last_error = error
                logger.warning("LLM JSON parse/validation failed (attempt %s)", attempt + 1)
        raise RuntimeError(f"LLM returned invalid structured output: {last_error}")

    def analyze_objective(self, work_request: WorkRequest) -> ObjectiveAnalysis:
        result = self.chat_json(
            f"Work request:\n{work_request.model_dump_json(indent=2)}",
            ObjectiveAnalysis,
        )
        if not isinstance(result, ObjectiveAnalysis):
            raise RuntimeError("analyze_objective returned the wrong schema")
        return result

    def extract_procedures(self, work_request: WorkRequest) -> ProcedureExtraction:
        result = self.chat_json(
            f"Work request:\n{work_request.model_dump_json(indent=2)}\n"
            "Identify organizational procedures that apply to this work. "
            "If none are known, return an empty procedures list.",
            ProcedureExtraction,
        )
        if not isinstance(result, ProcedureExtraction):
            raise RuntimeError("extract_procedures returned the wrong schema")
        return result

    def extract_requirements(self, work_request: WorkRequest) -> RequirementExtraction:
        result = self.chat_json(
            f"Work request:\n{work_request.model_dump_json(indent=2)}\n"
            "Extract the organizational requirements (process, policy, "
            "approval, evidence) that this work must satisfy. Use stable "
            "requirement IDs such as req_1, req_2.",
            RequirementExtraction,
        )
        if not isinstance(result, RequirementExtraction):
            raise RuntimeError("extract_requirements returned the wrong schema")
        return result


def create_llm_provider(settings: Settings) -> LLMProvider:
    provider = settings.llm_provider.lower().strip()

    if provider in {"nvidia", "openai", "openai-compatible"}:
        from langchain_openai import ChatOpenAI

        model = settings.resolved_llm_model
        api_key = settings.resolved_llm_api_key
        base_url = settings.resolved_llm_base_url

        if not model:
            raise ValueError("LLM_MODEL is required for cloud LLM providers.")
        if not api_key:
            raise ValueError("LLM_API_KEY is required for cloud LLM providers.")
        if not base_url:
            raise ValueError("LLM_BASE_URL is required for cloud LLM providers.")

        llm_kwargs = {
            "model": model,
            "api_key": api_key,
            "base_url": base_url,
            "temperature": 0,
            "timeout": 120,
            "max_retries": 0,
        }

        llm = ChatOpenAI(**llm_kwargs)
        return LangChainStructuredProvider(llm)

    if provider == "ollama":
        from langchain_ollama import ChatOllama

        model = getattr(settings, "ollama_model", None)
        if not model:
            raise ValueError("OLLAMA_MODEL is required when LLM_PROVIDER=ollama.")
        return LangChainStructuredProvider(
            ChatOllama(model=model, base_url=settings.ollama_base_url)
        )

    if provider == "mock":
        return MockLLMProvider()

    raise ValueError(
        f"Unsupported LLM_PROVIDER: {provider}. "
        "Expected one of: nvidia, openai, openai-compatible, ollama, mock."
    )